### ISSUE TITLE
cannot find package

### ISSUE THREAD

**Issue by beamzer** [Grayda/go-orvibo#2]
I am completely new to go, so excuse my ignorance.
Just installed golang on my debian system and
followed the readme and ran:
`pi@domoticz ~/go-orvibo/tests $ go run main.go`
which gave me:
`main.go:8:2: import "github.com/Grayda/go-orvibo": cannot find package
main.go:9:2: import "github.com/davecgh/go-spew/spew": cannot find package`

am i missing some software, or doing something wrong?

thanks in advance,

**Comment by paulcull** [comment]
Hi - try running <code>go get</code> to install dependences

https://golang.org/cmd/go/

**Comment by Grayda** [comment]
Hi @beamzer, did Paul's suggestion end up working for you? Let me know so I can close this issue if necessary. Thanks :)

**Comment by beamzer** [comment]
Hi, I ran "go get" but that also gives an error:
`pi@domoticz ~/go-orvibo $ go get
can't load package: package .: found packages orvibo (orvibo.go) and orvibo2 (orvibo2.go) in /home/pi/go-orvibo
`
To be sure, i ran a hello world example in go, but that works fine.
Will remove the golang i got through apt-get (version 1.02) and
try with version 1.5, see if that helps

**Comment by Grayda** [comment]
I think that's my mistake. Try deleting orvibo2.go and running `go get` again. orvibo2.go is / was a rewrite I was working on that never quite eventuated. I never picked up on the conflict because I already had the necessary packages and didn't need to run `go get`

**Comment by beamzer** [comment]
Hi David, that seemed to help a little, but i'm not quite there yet
`pi@domoticz ~/go-orvibo $ go get`
`package github.com/davecgh/go-spew/spew: mkdir /usr/lib/go/src/pkg/github.com: permission denied`

`pi@domoticz ~/go-orvibo $ sudo go get`
`go install: no install location for _/home/pi/go-orvibo`

`pi@domoticz ~/go-orvibo $ go run orvibo.go`
`go run: cannot run non-main package`

`pi@domoticz ~/go-orvibo $ go version`
`go version go1.0.2`

**Comment by Grayda** [comment]
I think you might need to set your GOROOT and GOPATH environment settings: https://golang.org/cmd/go/#hdr-GOPATH_environment_variable , plus set up your folder structure for running Go projects: https://golang.org/doc/code.html#Workspaces

GOROOT should be the location of your Go installation (e.g. `~/go`) and GOPATH should be where your project reside (e.g. `~/go-projects`)

Your folder structure (put it somewhere like `~/go-projects`) would generally have three folders within it -- `pkg`, `src` and `bin` -- `src` is for source code, `pkg` is for intermediate files and `bin` would be for the final binary that you can run.

Also, can you run `go env` and copy the output? That should tell you what your GOROOT and GOPATH environment variables are set to.

**Comment by beamzer** [comment]
Ok, i have got the test running now.
thanks for your patience and getting me there!

domoticz:~/go-orvibo/tests> go run main.go
UDP connection ready
Subscribing to devices
Socket found! MAC address is accf23560c46
Subscription successful!
======== 686400006463accfdeadbeef2020202020203ef5ee0b5684012b00daaeeb
======== 686400006463accfdeadbeef2020202020203ef5ee0b7afe012b00daaeeb
Trying to parse the state of an RF switch. If this fails, please pass this info on to the developer!
686400196463accf23560c4620202020202009000000005684
RF switch pressed
(map[string]orvibo.RFSwitch) (len=1) {
(string) (len=6) "090000": (orvibo.RFSwitch) {
  State: (bool) true
}
}
Trying to parse the state of an RF switch. If this fails, please pass this info on to the developer!
686400196463accf23560c4620202020202009000000007afe
RF switch pressed
(map[string]orvibo.RFSwitch) (len=1) {
(string) (len=6) "090000": (orvibo.RFSwitch) {
  State: (bool) true
}
}
Socket found! MAC address is accf23560c46
Querying any unqueried devices

**Comment by Grayda** [comment]
Glad to hear you got it working. Golang can be a tricky language to set up, get running and keep maintained, but overall it's a fun language to learn.
